### ISSUE TITLE
How do you build the Obsidian notes graph?

### ISSUE THREAD

**Issue by xplosionmind** [EllyLoel/ellyloel.com#148]
Hi! I have [a Zettlekasten myself](https://tommi.space/jam 'The Jam'), and I am wondering how did you build your notes graph:

![Screenshot 2022-11-01 at 7 49 13 PM](https://user-images.githubusercontent.com/42862428/199314141-8a06a20c-9403-4a42-bca3-4d16f319d17a.jpg)

**Comment by EllyLoel** [comment]
Hey! I built the graph with D3.js, here's the code:

https://github.com/EllyLoel/ellyloel.com/blob/main/src/js/graph.js

https://github.com/EllyLoel/ellyloel.com/blob/main/src/js/force-graph.js
