### ISSUE TITLE
Values in CSS reset are invisible

### ISSUE THREAD

**Issue by edwinm** [EllyLoel/ellyloel.com#267]
When I visit your CSS reset

https://www.ellyloel.com/projects/modern-css-reset/

In Chrome 130.0.6723.92 on MacOS,

The values are invisible.

In Firefox I see the same problem when I switch it to light mode.

See this screenshot:

<img width="911" alt="image" src="https://github.com/user-attachments/assets/cdeb588b-538a-406b-b328-a3634e3e469b">

**Comment by EllyLoel** [comment]
Thanks for noticing that and letting me know!
